// Code generated by stanc v2.33.1
#include <stan/model/model_header.hpp>
namespace vanilla_rsa_copy_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 43> locations_array__ =
  {" (found before start of program)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 19, column 2 to column 22)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 20, column 2 to column 28)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 24, column 2 to column 49)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 25, column 2 to column 53)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 27, column 2 to column 18)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 36, column 2 to column 18)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 29, column 15 to column 16)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 29, column 4 to column 28)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 31, column 6 to column 69)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 30, column 19 to line 32, column 5)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 30, column 4 to line 32, column 5)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 33, column 4 to column 35)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 28, column 17 to line 34, column 3)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 28, column 2 to line 34, column 3)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 38, column 15 to column 16)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 38, column 4 to column 30)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 40, column 8 to column 71)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 39, column 19 to line 41, column 5)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 39, column 4 to line 41, column 5)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 42, column 4 to column 37)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 37, column 17 to line 43, column 3)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 37, column 2 to line 43, column 3)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 48, column 2 to column 23)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 49, column 2 to column 29)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 52, column 2 to column 40)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 8, column 2 to column 17)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 9, column 2 to column 17)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 11, column 26 to column 27)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 11, column 29 to column 30)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 11, column 2 to column 47)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 12, column 9 to column 10)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 12, column 2 to column 17)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 14, column 2 to column 19)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 15, column 2 to column 19)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 24, column 9 to column 10)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 25, column 9 to column 10)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 27, column 9 to column 10)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 27, column 12 to column 13)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 36, column 9 to column 10)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 36, column 12 to column 13)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 3, column 4 to column 51)",
  " (in 'C:/Users/User/PROTON~1/maa_ng0h/MYFILE~1/C1F03~1.WOR/2EMODE~1/STUDYP~1/stan/vanilla_rsa_copy.stan', line 2, column 47 to line 4, column 3)"};
template <typename T0__,
          stan::require_all_t<stan::is_row_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,1,-1>
softmax_log(const T0__& log_probs_arg__, std::ostream* pstream__);
// row_vector softmax_log(row_vector)
template <typename T0__,
          stan::require_all_t<stan::is_row_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,1,-1>
softmax_log(const T0__& log_probs_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& log_probs = stan::math::to_ref(log_probs_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 41;
    return stan::math::exp(
             stan::math::subtract(log_probs,
               stan::math::log_sum_exp(log_probs)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class vanilla_rsa_copy_model final : public model_base_crtp<vanilla_rsa_copy_model> {
 private:
  int S;
  int U;
  Eigen::Matrix<double,-1,-1> meaning_matrix_data__;
  Eigen::Matrix<double,-1,1> cost_data__;
  int utt;
  int tar;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> meaning_matrix{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> cost{nullptr, 0};
 public:
  ~vanilla_rsa_copy_model() {}
  vanilla_rsa_copy_model(stan::io::var_context& context__, unsigned int
                         random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "vanilla_rsa_copy_model_namespace::vanilla_rsa_copy_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 26;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 26;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "U", "int",
        std::vector<size_t>{});
      U = std::numeric_limits<int>::min();
      current_statement__ = 27;
      U = context__.vals_i("U")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "U", U, 1);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("meaning_matrix", "U", U);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("meaning_matrix", "S", S);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "meaning_matrix",
        "double",
        std::vector<size_t>{static_cast<size_t>(U), static_cast<size_t>(S)});
      meaning_matrix_data__ = Eigen::Matrix<double,-1,-1>::Constant(U, S,
                                std::numeric_limits<double>::quiet_NaN());
      new (&meaning_matrix)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(meaning_matrix_data__.data(),
        U, S);
      {
        std::vector<local_scalar_t__> meaning_matrix_flat__;
        current_statement__ = 30;
        meaning_matrix_flat__ = context__.vals_r("meaning_matrix");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= U; ++sym2__) {
            stan::model::assign(meaning_matrix, meaning_matrix_flat__[(pos__
              - 1)], "assigning variable meaning_matrix",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "meaning_matrix",
        meaning_matrix, 0);
      current_statement__ = 30;
      stan::math::check_less_or_equal(function__, "meaning_matrix",
        meaning_matrix, 1);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("cost", "U", U);
      current_statement__ = 32;
      context__.validate_dims("data initialization", "cost", "double",
        std::vector<size_t>{static_cast<size_t>(U)});
      cost_data__ = Eigen::Matrix<double,-1,1>::Constant(U,
                      std::numeric_limits<double>::quiet_NaN());
      new (&cost) Eigen::Map<Eigen::Matrix<double,-1,1>>(cost_data__.data(),
        U);
      {
        std::vector<local_scalar_t__> cost_flat__;
        current_statement__ = 32;
        cost_flat__ = context__.vals_r("cost");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= U; ++sym1__) {
          stan::model::assign(cost, cost_flat__[(pos__ - 1)],
            "assigning variable cost", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 33;
      context__.validate_dims("data initialization", "utt", "int",
        std::vector<size_t>{});
      utt = std::numeric_limits<int>::min();
      current_statement__ = 33;
      utt = context__.vals_i("utt")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "utt", utt, 1);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "tar", "int",
        std::vector<size_t>{});
      tar = std::numeric_limits<int>::min();
      current_statement__ = 34;
      tar = context__.vals_i("tar")[(1 - 1)];
      current_statement__ = 34;
      stan::math::check_greater_or_equal(function__, "tar", tar, 1);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("state_prior", "S", S);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("utterance_prior", "U", U);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("L0", "U", U);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("L0", "S", S);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("S1", "S", S);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("S1", "U", U);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1;
  }
  inline std::string model_name() const final {
    return "vanilla_rsa_copy_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.33.1",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "vanilla_rsa_copy_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ cost_weight = DUMMY_VAR__;
      current_statement__ = 2;
      cost_weight = in__.template read_constrain_lb<local_scalar_t__,
                      jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> state_prior =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(state_prior, stan::math::rep_vector((1.0 / S), S),
        "assigning variable state_prior");
      Eigen::Matrix<local_scalar_t__,-1,1> utterance_prior =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(U, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(utterance_prior,
        stan::math::rep_vector((1.0 / U), U),
        "assigning variable utterance_prior");
      Eigen::Matrix<local_scalar_t__,-1,-1> L0 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(U, S, DUMMY_VAR__);
      current_statement__ = 14;
      for (int u = 1; u <= U; ++u) {
        current_statement__ = 7;
        stan::math::validate_non_negative_index("log_probs", "S", S);
        Eigen::Matrix<local_scalar_t__,1,-1> log_probs =
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 11;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 9;
          stan::model::assign(log_probs,
            (stan::math::log(
               stan::model::rvalue(meaning_matrix, "meaning_matrix",
                 stan::model::index_uni(u), stan::model::index_uni(s))) +
            stan::math::log(
              stan::model::rvalue(state_prior, "state_prior",
                stan::model::index_uni(s)))), "assigning variable log_probs",
            stan::model::index_uni(s));
        }
        current_statement__ = 12;
        stan::model::assign(L0, softmax_log(log_probs, pstream__),
          "assigning variable L0", stan::model::index_uni(u));
      }
      Eigen::Matrix<local_scalar_t__,-1,-1> S1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, U, DUMMY_VAR__);
      current_statement__ = 22;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 15;
        stan::math::validate_non_negative_index("log_utility", "U", U);
        Eigen::Matrix<local_scalar_t__,1,-1> log_utility =
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(U, DUMMY_VAR__);
        current_statement__ = 19;
        for (int u = 1; u <= U; ++u) {
          current_statement__ = 17;
          stan::model::assign(log_utility, ((alpha *
            stan::math::log(
              stan::model::rvalue(L0, "L0", stan::model::index_uni(u),
                stan::model::index_uni(s)))) - (cost_weight *
            stan::model::rvalue(cost, "cost", stan::model::index_uni(u)))),
            "assigning variable log_utility", stan::model::index_uni(u));
        }
        current_statement__ = 20;
        stan::model::assign(S1, softmax_log(log_utility, pstream__),
          "assigning variable S1", stan::model::index_uni(s));
      }
      {
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha, 5, 5));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(cost_weight, 1, 1));
        current_statement__ = 25;
        lp_accum__.add(stan::math::categorical_lpmf<propto__>(utt,
                         stan::math::to_vector(
                           stan::model::rvalue(S1, "S1",
                             stan::model::index_uni(tar)))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "vanilla_rsa_copy_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ cost_weight = DUMMY_VAR__;
      current_statement__ = 2;
      cost_weight = in__.template read_constrain_lb<local_scalar_t__,
                      jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> state_prior =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(state_prior, stan::math::rep_vector((1.0 / S), S),
        "assigning variable state_prior");
      Eigen::Matrix<local_scalar_t__,-1,1> utterance_prior =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(U, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(utterance_prior,
        stan::math::rep_vector((1.0 / U), U),
        "assigning variable utterance_prior");
      Eigen::Matrix<local_scalar_t__,-1,-1> L0 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(U, S, DUMMY_VAR__);
      current_statement__ = 14;
      for (int u = 1; u <= U; ++u) {
        current_statement__ = 7;
        stan::math::validate_non_negative_index("log_probs", "S", S);
        Eigen::Matrix<local_scalar_t__,1,-1> log_probs =
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 11;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 9;
          stan::model::assign(log_probs,
            (stan::math::log(
               stan::model::rvalue(meaning_matrix, "meaning_matrix",
                 stan::model::index_uni(u), stan::model::index_uni(s))) +
            stan::math::log(
              stan::model::rvalue(state_prior, "state_prior",
                stan::model::index_uni(s)))), "assigning variable log_probs",
            stan::model::index_uni(s));
        }
        current_statement__ = 12;
        stan::model::assign(L0, softmax_log(log_probs, pstream__),
          "assigning variable L0", stan::model::index_uni(u));
      }
      Eigen::Matrix<local_scalar_t__,-1,-1> S1 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, U, DUMMY_VAR__);
      current_statement__ = 22;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 15;
        stan::math::validate_non_negative_index("log_utility", "U", U);
        Eigen::Matrix<local_scalar_t__,1,-1> log_utility =
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(U, DUMMY_VAR__);
        current_statement__ = 19;
        for (int u = 1; u <= U; ++u) {
          current_statement__ = 17;
          stan::model::assign(log_utility, ((alpha *
            stan::math::log(
              stan::model::rvalue(L0, "L0", stan::model::index_uni(u),
                stan::model::index_uni(s)))) - (cost_weight *
            stan::model::rvalue(cost, "cost", stan::model::index_uni(u)))),
            "assigning variable log_utility", stan::model::index_uni(u));
        }
        current_statement__ = 20;
        stan::model::assign(S1, softmax_log(log_utility, pstream__),
          "assigning variable S1", stan::model::index_uni(s));
      }
      {
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha, 5, 5));
        current_statement__ = 24;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(cost_weight, 1, 1));
        current_statement__ = 25;
        lp_accum__.add(stan::math::categorical_lpmf<propto__>(utt,
                         stan::math::to_vector(
                           stan::model::rvalue(S1, "S1",
                             stan::model::index_uni(tar)))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "vanilla_rsa_copy_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double cost_weight = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      cost_weight = in__.template read_constrain_lb<local_scalar_t__,
                      jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> state_prior =
        Eigen::Matrix<double,-1,1>::Constant(S,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> utterance_prior =
        Eigen::Matrix<double,-1,1>::Constant(U,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> L0 =
        Eigen::Matrix<double,-1,-1>::Constant(U, S,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> S1 =
        Eigen::Matrix<double,-1,-1>::Constant(S, U,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(alpha);
      out__.write(cost_weight);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 3;
      stan::model::assign(state_prior, stan::math::rep_vector((1.0 / S), S),
        "assigning variable state_prior");
      current_statement__ = 4;
      stan::model::assign(utterance_prior,
        stan::math::rep_vector((1.0 / U), U),
        "assigning variable utterance_prior");
      current_statement__ = 14;
      for (int u = 1; u <= U; ++u) {
        current_statement__ = 7;
        stan::math::validate_non_negative_index("log_probs", "S", S);
        Eigen::Matrix<double,1,-1> log_probs =
          Eigen::Matrix<double,1,-1>::Constant(S,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 11;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 9;
          stan::model::assign(log_probs,
            (stan::math::log(
               stan::model::rvalue(meaning_matrix, "meaning_matrix",
                 stan::model::index_uni(u), stan::model::index_uni(s))) +
            stan::math::log(
              stan::model::rvalue(state_prior, "state_prior",
                stan::model::index_uni(s)))), "assigning variable log_probs",
            stan::model::index_uni(s));
        }
        current_statement__ = 12;
        stan::model::assign(L0, softmax_log(log_probs, pstream__),
          "assigning variable L0", stan::model::index_uni(u));
      }
      current_statement__ = 22;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 15;
        stan::math::validate_non_negative_index("log_utility", "U", U);
        Eigen::Matrix<double,1,-1> log_utility =
          Eigen::Matrix<double,1,-1>::Constant(U,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 19;
        for (int u = 1; u <= U; ++u) {
          current_statement__ = 17;
          stan::model::assign(log_utility, ((alpha *
            stan::math::log(
              stan::model::rvalue(L0, "L0", stan::model::index_uni(u),
                stan::model::index_uni(s)))) - (cost_weight *
            stan::model::rvalue(cost, "cost", stan::model::index_uni(u)))),
            "assigning variable log_utility", stan::model::index_uni(u));
        }
        current_statement__ = 20;
        stan::model::assign(S1, softmax_log(log_utility, pstream__),
          "assigning variable S1", stan::model::index_uni(s));
      }
      if (emit_transformed_parameters__) {
        out__.write(state_prior);
        out__.write(utterance_prior);
        out__.write(L0);
        out__.write(S1);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      local_scalar_t__ cost_weight = DUMMY_VAR__;
      current_statement__ = 2;
      cost_weight = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, cost_weight);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "cost_weight",
        "double", std::vector<size_t>{});
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      out__.write_free_lb(0, alpha);
      local_scalar_t__ cost_weight = DUMMY_VAR__;
      current_statement__ = 2;
      cost_weight = context__.vals_r("cost_weight")[(1 - 1)];
      out__.write_free_lb(0, cost_weight);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha", "cost_weight"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"state_prior", "utterance_prior", "L0", "S1"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(S)},
             std::vector<size_t>{static_cast<size_t>(U)},
             std::vector<size_t>{static_cast<size_t>(U),
               static_cast<size_t>(S)},
             std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(U)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "cost_weight");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        param_names__.emplace_back(std::string() + "state_prior" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= U; ++sym1__) {
        param_names__.emplace_back(std::string() + "utterance_prior" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= U; ++sym2__) {
          param_names__.emplace_back(std::string() + "L0" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= U; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "S1" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "cost_weight");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        param_names__.emplace_back(std::string() + "state_prior" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= U; ++sym1__) {
        param_names__.emplace_back(std::string() + "utterance_prior" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= U; ++sym2__) {
          param_names__.emplace_back(std::string() + "L0" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= U; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "S1" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"cost_weight\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"state_prior\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"},{\"name\":\"utterance_prior\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(U) + "},\"block\":\"transformed_parameters\"},{\"name\":\"L0\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(U) + ",\"cols\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"},{\"name\":\"S1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(U) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"cost_weight\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"state_prior\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"},{\"name\":\"utterance_prior\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(U) + "},\"block\":\"transformed_parameters\"},{\"name\":\"L0\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(U) + ",\"cols\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"},{\"name\":\"S1\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(U) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((S + U) +
      (U * S)) + (S * U)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * ((((S + U) +
      (U * S)) + (S * U)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = vanilla_rsa_copy_model_namespace::vanilla_rsa_copy_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return vanilla_rsa_copy_model_namespace::profiles__;
}
#endif